# Generated by Django 5.0.1 on 2025-04-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_firebaseuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebaseuser',
            name='role',
        ),
    ]
