# Generated by Django 5.0.1 on 2025-04-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_firebaseuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
