# Generated by Django 5.0.1 on 2025-04-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcategory',
            name='slug',
        ),
    ]
