# Generated by Django 5.0.1 on 2025-04-25 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_jobcategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('location', models.CharField(max_length=200)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship'), ('Volunteer', 'Volunteer')], max_length=20)),
                ('job_category', models.CharField(choices=[('IT', 'IT'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Education', 'Education'), ('Marketing', 'Marketing'), ('Engineering', 'Engineering'), ('Design', 'Design'), ('Customer Service', 'Customer Service')], max_length=20)),
                ('no_of_employees', models.CharField(blank=True, max_length=100)),
                ('posted_by', models.CharField(blank=True, max_length=200)),
                ('job_description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('qualifications', models.TextField()),
                ('skills', models.TextField(blank=True)),
                ('salary_and_benefits', models.TextField(blank=True)),
                ('how_to_apply', models.TextField(blank=True)),
                ('encourage_applicants', models.TextField(blank=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('posted_on', models.DateField(default=django.utils.timezone.now)),
                ('expired_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Draft', 'Draft')], default='Active', max_length=10)),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
