# Generated by Django 5.0.1 on 2025-04-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobposting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPosting',
        ),
    ]
