# Generated by Django 5.0.1 on 2025-05-08 16:37

from django.db import migrations

def create_locations_and_update_jobs(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    Location = apps.get_model('jobs', 'Location')
    db_alias = schema_editor.connection.alias

    # Get all unique location names from jobs
    unique_locations = set(Job.objects.using(db_alias).values_list('location', flat=True))
    name_to_obj = {}
    for loc_name in unique_locations:
        if loc_name:
            obj, created = Location.objects.using(db_alias).get_or_create(name=loc_name)
            name_to_obj[loc_name] = obj

    # Update each job to use the Location FK
    for job in Job.objects.using(db_alias).all():
        if job.location and job.location in name_to_obj:
            job.location = name_to_obj[job.location]
            job.save()

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_location_alter_job_location'),
    ]

    operations = [
        migrations.RunPython(create_locations_and_update_jobs),
    ]
