# Generated by Django 5.0.1 on 2025-05-08 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_location_fk_alter_job_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location_fk',
        ),
        migrations.AlterField(
            model_name='job',
            name='expired_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_on',
            field=models.DateField(null=True),
        ),
    ]
