# Generated by Django 5.0.1 on 2025-05-08 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_job_location_fk_alter_job_expired_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.location'),
        ),
    ]
