# Generated by Django 5.0.1 on 2025-05-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_location_text_alter_job_location'),
    ]

    operations = [
    ]
