# Generated by Django 5.0.1 on 2025-05-08 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_migrate_location_text_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location_text',
        ),
        migrations.AlterField(
            model_name='job',
            name='how_to_apply',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=models.TextField(),
        ),
    ]
