# Generated by Django 5.0.1 on 2025-04-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'expired'), ('Expired', 'active')], default='Draft', max_length=10),
        ),
    ]
