# Generated by Django 5.0.1 on 2025-04-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0002_alter_jobpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Expired', 'Expired')], default='Draft', max_length=10),
        ),
    ]
