# Generated by Django 5.0.1 on 2025-04-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0003_alter_jobpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship'), ('Volunteer', 'Volunteer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_category',
            field=models.CharField(blank=True, choices=[('Architecture & Construction', 'Architecture & Construction'), ('Construction', 'Construction'), ('Engineering', 'Engineering'), ('Accounting', 'Accounting'), ('Finance', 'Finance'), ('Customer Service', 'Customer Service'), ('Professional Services', 'Professional Services'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Information Technology', 'Information Technology'), ('Telecommunications', 'Telecommunications'), ('Community Service', 'Community Service'), ('Science & Technology', 'Science & Technology'), ('Business & Administration', 'Business & Administration'), ('Media & Journalism', 'Media & Journalism'), ('Advertising and Media', 'Advertising and Media'), ('Sales', 'Sales'), ('Management', 'Management'), ('Admin, Secretarial & Clerical', 'Admin, Secretarial & Clerical'), ('Legal', 'Legal'), ('Restaurant & Food Service', 'Restaurant & Food Service'), ('Purchasing & Procurement', 'Purchasing & Procurement'), ('Business Development', 'Business Development'), ('QA-Quality Control', 'QA-Quality Control'), ('Inventory & Stock', 'Inventory & Stock'), ('Insurance', 'Insurance'), ('Economics', 'Economics'), ('Social Science & Community', 'Social Science & Community'), ('Communications, PR & Journalism', 'Communications, PR & Journalism'), ('Environment & Natural Resource', 'Environment & Natural Resource'), ('Hospitality-Hotel', 'Hospitality-Hotel'), ('Supply Chain', 'Supply Chain'), ('Warehouse', 'Warehouse'), ('Natural Science', 'Natural Science'), ('Retail and Trade', 'Retail and Trade'), ('Nurse', 'Nurse'), ('Logistics, Transport & Supply Chain', 'Logistics, Transport & Supply Chain'), ('Human Resources', 'Human Resources'), ('Development & Project Management', 'Development & Project Management'), ('Training', 'Training'), ('Installation & Repair', 'Installation & Repair'), ('Education', 'Education'), ('Health Care', 'Health Care'), ('Agriculture and Food', 'Agriculture and Food'), ('General Business', 'General Business'), ('Research', 'Research'), ('Consultancy & Training', 'Consultancy & Training'), ('Travel & Tourism', 'Travel & Tourism'), ('Manufacturing', 'Manufacturing'), ('Maintenance', 'Maintenance'), ('Distribution-Shipping', 'Distribution-Shipping')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
    ]
