# Generated by Django 5.0.1 on 2025-05-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0004_alter_jobpost_employment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Approved', 'Approved'), ('Expired', 'Expired')], default='Draft', max_length=10),
        ),
    ]
