# Generated by Django 5.0.1 on 2025-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0005_alter_jobpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_new_for_admin',
            field=models.BooleanField(default=True),
        ),
    ]
