# Generated by Django 5.0.1 on 2025-05-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0006_jobpost_is_new_for_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
