# Generated by Django 5.0.1 on 2025-05-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0007_jobpost_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['approved', '-created_at'], 'verbose_name': 'Job Post', 'verbose_name_plural': 'Job Posts'},
        ),
    ]
