# Generated by Django 5.0.1 on 2025-05-08 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0008_alter_jobpost_options'),
        ('jobs', '0014_remove_job_location_text_alter_job_how_to_apply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.location'),
        ),
    ]
