# Generated by Django 5.0.1 on 2025-05-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0009_alter_jobpost_location'),
    ]

    operations = [
    ]
