# Generated by Django 5.0.1 on 2025-05-08 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0010_convert_location_data'),
        ('jobposting', '0010_convert_locations'),
    ]

    operations = [
    ]
