# Generated by Django 5.0.1 on 2025-07-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0012_alter_jobpost_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_created',
            field=models.BooleanField(default=False),
        ),
    ]
